=== sandranics/Recipe-Catalog-XML2023-Uni-Project/XML2022_project_project13_62541_62546.dtd
<!ELEMENT catalog (regions, techniques-to-prepare, recipes)>
<!ELEMENT regions (region+)>
<!ELEMENT region EMPTY>
<!ATTLIST region name CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT techniques-to-prepare (technique+)>
<!ELEMENT technique EMPTY>
<!ATTLIST technique name CDATA #REQUIRED id ID #REQUIRED>
<!ELEMENT recipes (recipe+)>
<!ELEMENT recipe (name, image, author, origin, ingredients, preparation-steps, how-to-serve, suitable-drinks, medical-parameters, allergens)>
<!ATTLIST recipe ID CDATA #REQUIRED region-ID IDREF #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name food-type CDATA #IMPLIED> 
<!ELEMENT image EMPTY>
<!ATTLIST image href ENTITY #REQUIRED>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author nationality CDATA #IMPLIED> 
<!ELEMENT origin (#PCDATA)>
<!ELEMENT ingredients (list)>
<!ELEMENT list (item+)>
<!ELEMENT item (#PCDATA)>
<!ELEMENT preparation-steps (#PCDATA)>
<!ATTLIST preparation-steps technique-ID IDREF #REQUIRED>
<!ELEMENT how-to-serve (#PCDATA)>
<!ELEMENT suitable-drinks (#PCDATA)>
<!ELEMENT medical-parameters (#PCDATA)>
<!ELEMENT allergens (allergen+)>
<!ELEMENT allergen (#PCDATA)>
<!NOTATION jpg PUBLIC "jpg viewer">

=== sandranics/Recipe-Catalog-XML2023-Uni-Project/XML2022_project_project13_62541_62546.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="XML2022_project_project13_62541_62546.xsl"?>
<!DOCTYPE catalog SYSTEM "XML2022_project_project13_62541_62546.dtd" [
	<!ENTITY bobchorba SYSTEM "images/bobchorba.jpg" NDATA jpg>
	<!ENTITY byalmazh SYSTEM "images/byalmazh.jpg" NDATA jpg>
	<!ENTITY chomlek SYSTEM "images/chomlek.jpg" NDATA jpg>
	<!ENTITY kapama SYSTEM "images/kapama.jpg" NDATA jpg>
	<!ENTITY kosachkokiselo SYSTEM "images/kosachkokiselo.jpg" NDATA jpg>
	<!ENTITY patatnik SYSTEM "images/patatnik.jpg" NDATA jpg>
	<!ENTITY ribenachorba SYSTEM "images/ribenachorba.jpg" NDATA jpg>
	<!ENTITY shopskasalata SYSTEM "images/shopskasalata.jpg" NDATA jpg>
	<!ENTITY taramahaiver SYSTEM "images/taramahaiver.jpg" NDATA jpg>
	<!ENTITY tortagarash SYSTEM "images/tortagarash.jpg" NDATA jpg>
]>

<catalog>
	<regions>
		<region name="Северозападен" id="NW"/>
		<region name="Северен централен" id="NC"/>
		<region name="Североизточен" id="NE"/>
		<region name="Югозападен" id="SW"/>
		<region name="Южен централен" id="SC"/>
		<region name="Югоизточен" id="SE"/>
		<region name="Незнаен" id="NA"/>
	</regions>
	<techniques-to-prepare>
		<technique name="Печене" id="PE"/>
		<technique name="Пържене" id="PR"/>
		<technique name="Варене" id="VA"/>
		<technique name="Пасиране" id="PA"/>
		<technique name="Нито едно от изброените" id="NN"/>
	</techniques-to-prepare>
	<recipes>
		<recipe ID="Tорта Гараш" region-ID="NC">
			<name food-type="Десерт">Tорта "Гараш"</name>
			<image href="tortagarash"/>
			<author nationality="Австро-Унгария">Коста Гараш</author>
			<origin>Легендарната торта "Гараш" започва славния си път от... България! Оказва се, че вкусният шоколадов деликатес за пръв път е представен у нас преди близо 120 години!
През 1885 г. в Русе пристига прочут сладкар – Коста Гараш от Австро-Унгария. Сладкото изкушение, което той измисля, носи именно неговото име. но как започва всичко?
В края на XIX век в Русе е построен първият за България гранд хотел – „Ислях хане”. Мебелите, приборите, завесите са специално доставени от Виена и блясъкът на тогавашна Австро-Унгария се пренася в Русе. Когато пристига в града, Коста Гараш поема управлението на „Ислях хане”.
Краят на XIX век, основния салон на хотел "Ислях хане" в Русе
В салоните на хотела княз Александър Батенберг посреща крале. Именно за един от тези приеми Гараш създава тортата „Гараш”. След това я пренася в София в един от най-луксозните хотели за онова време – „Пахах”. Около 1900 година Коста Гараш се премества в София, за да поеме управлението на хотела. На партера се е намирала и сладкарницата, където столичани са можели да опитат парче „Гараш”.</origin>
			<ingredients>
				<list>
					<item>200 гр. орехи</item>
					<item>8 яйца</item>
					<item>220 гр. пудра захар</item>
					<item>20 гр. брашно</item>
					<item>400 мл. сладкарска сметана</item>
					<item>500 гр. черен шоколад</item>
				</list>
			</ingredients>
			<preparation-steps technique-ID="PE">Правят се  пет тънки блата направени от смес, съдържаща 200 грама орехи, 8 яйца, 220 грама пудра захар и 20 грама брашно. Всеки блат се пече върху намазнена оризова хартия при умерена температура до порозовяване, след което се оставя да изстине. Сметаната се разбива до сгъстяване, ако не е сладка се добавя захар. Шоколадът се разтопява на водна баня и по-голяма част от него се добавя към вече разбитата сладка сметана. Бърка се до получаване на еднороден шоколадов крем, към който може да се добави ром или коняк. Блатовете се редят, като всеки се маже обилно с шоколадовия мус. Накрая цялата торта се покрива с шоколадова глазура и се украсява с оцветени в зелено кокосови стърготини или филирани бадеми. Оставя да пренощува в хладилник  на хладно, за да стегне.</preparation-steps>
			<how-to-serve>Сервира се на другия ден студена.</how-to-serve>
			<suitable-drinks>Върви с напитка Ликьорено бяло вино , Коняк , Бейлис</suitable-drinks>
			<medical-parameters>Тортата е много калорична и се препоръчва за хора на диета да се ограничат с едно парче. За хора с хранителни алергии не трябва да я консумират.</medical-parameters>
			<allergens>
				<allergen>брашно-гултен</allergen>
				<allergen>яйца</allergen>
				<allergen>шоколад</allergen>
				<allergen>бадеми</allergen>
			</allergens>
		</recipe>
		<recipe ID="Шопска салата" region-ID="NA">
			<name food-type="Предястие">Шопска салата</name>
			<image href="shopskasalata"/>
			<author nationality="България">ДСП „Балкантурист“</author>
			<origin>Шопската салата е създадена от професионални майстори-готвачи от ДСП „Балкантурист“ през 1956 г. в ресторант „Черноморец“ в тогавашния курорт „Дружба“ (днес „Свети Константин и Елена“) В началото на 1970-те години печените чушки и настърганото сирене се налагат като задължителен елемент от салатата .Първоначално шопската салата се сервира в заведенията на ДСО „Балкантурист“, откъдето се налага и в домашната кухня. Утвърждава се като национален кулинарен символ през 1970-те и 1980-те години. От България рецептата се разпространява и в кухнята на съседните страни.</origin>
			<ingredients>
				<list>
					<item>400 гр. домати</item>
					<item>250 гр. краставици</item>
					<item>1 бр. червена печена чушка</item>
					<item>1 глава кромид лук</item>
					<item>200 гр. краве сирене</item>
					<item>1/2 връзка магданоз</item>
					<item>оцет</item>
					<item>олио</item>
					<item>сол</item>
					<item>маслини</item>
					<item>зелени чушки за украса</item>
					<item>няколко стръкчета магданоз за гарниране</item>
				</list>
			</ingredients>
			<preparation-steps technique-ID="NN">Доматите, краставиците, печената чушка, лук и магданоз се нарязват. Овкусява се с оцет, олио и сол. Настъргва се сирене отгоре, зелената чушка се нарязва на колелца за декорация на чинията. Маслината се слага върху сиренето и стръкче магданоз .</preparation-steps>
			<how-to-serve>Сервира се студена.</how-to-serve>
			<suitable-drinks>Консумира се със студена ракия.</suitable-drinks>
			<medical-parameters>Доматите са  с високо съдържание на диетични фибри. Редовната им консумация в храната допринася за нормализирането на храносмилателния тракт, подобрявайки перисталтиката, отделянето на токсини  и други вредни вещества от организма. Червените чушки съдържат повече от 200 процента от дневния ви прием на витамин С. Освен че е мощен антиоксидант, витамин С помага за правилното усвояване на желязото.</medical-parameters>
			<allergens>
				<allergen>сирене</allergen>
				<allergen>казеин</allergen>
				<allergen>лактоглобулин</allergen>
			</allergens>
		</recipe>
		<recipe ID="Капама" region-ID="SW">
			<name food-type="Основно ястие">Капама</name>
			<image href="kapama"/>
			<author nationality="България">Unknown</author>
			<origin>Капама е традиционно българско национално ястие приготвяно от населението в котловината по поречието на река Места, наричана Разлог, в Югозападна България. Думата е с персийски произход.  Оригиналната капама се готви в казан върху открит огън. Сега е по-известен друг начин на приготвяне - в запечатано с тесто глинено гърне (гювеч) се пече няколко часа във фурна.</origin>
			<ingredients>
				<list>
					<item>500 гр. свинско месо</item>
					<item>500 гр. телешко месо</item>
					<item>500 гр. пиле</item>
					<item>1 кисела зелка</item>
					<item>1 чаша ориз</item>
					<item>400 гр. суджук</item>
					<item>400 гр. кървавица</item>
					<item>1 чаша червено вино</item>
					<item>черен пипер</item>
					<item>червен пипер</item>
					<item>сол на вкус</item>
					<item>тесто за замазване</item>
				</list>
			</ingredients>
			<preparation-steps technique-ID="PE">Поставете един слой от предварително фино нарязаното кисело зеле в глинен съд. Добавете малко подправки. Поставете един слой от ориз. После наредете част от  свинското, телешкото, пилешкото, както и парчета суджук и кървавица. Добавете още един слой от кисело зеле. Сложете подправките и поставете отново слой от всички видове месо. Продължете по същия начин, докато съдът се запълни. Затворете капака на съда с тесто. Поставете съда в студена фурна, печете на ниска температура (150 градуса). След като заври, печете най-малко 4 часа.</preparation-steps>
			<how-to-serve>Може да се сервира с картофено пюре или друга гарнитура по желание.</how-to-serve>
			<suitable-drinks>Ястието се сервира с червено вино.</suitable-drinks>
			<medical-parameters>Ястието е много калорично , да се консумира в умерено количество от хора на диета. Киселото зеле премахва стомашни проблеми, защото млечно-киселите бактерии в него, които действат противомикробно, влияят отлично върху чревната флора в полза на полезните чревни бактерии. Месото е едно от най-питателните храни и съдържа всички необходими аминокиселини за изграждане на мускули и кости.</medical-parameters>
			<allergens>
				<allergen>бяло вино</allergen>
				<allergen>сулфити</allergen>
				<allergen>хистамин</allergen>
			</allergens>
		</recipe>
		<recipe ID="Боб чорба по манастирски" region-ID="NA">
			<name food-type="Основно ястие">Боб чорба по манастирски</name>
			<image href="bobchorba"/>
			<author nationality="България">Unknown</author>
			<origin>Боб чорба по манастирски наистина идва от трапезата на манастирската кухня. Навремето монасите сами са отглеждали храната си, каквото си произведат това ще сложат на масата си.Отглеждали са зеленчуци, плодове, гледали са животни… И сега в някой от манастирите тази традиция продължава. Храната им е била скромна и често са похапвали боб.</origin>	 
			<ingredients>
				<list>
					<item>300 гр. бял боб</item>
					<item>1 глава лук</item>
					<item>2 глави чесън</item>
					<item>2 моркова</item>
					<item>2 пресни чушки</item>
					<item>1 връзка пресен лук, сол</item>
					<item>1 с.л. червен пипер</item>
					<item>50 мл олио</item>
					<item>1 връзка пресен джоджен</item>
					<item>1 люта чушка</item>
				</list>
			</ingredients>
